services:
    application:
          class:            Symfony\Component\Console\Application
    event_dispatcher:
          class:            Symfony\Component\EventDispatcher\EventDispatcher
    base_deploy_command:
          class:            Deploy\Extensions\Base\Command\DeployCommand
          tags:
              -
                   name:    'command'
    deploy:
          class:            Deploy\Extensions\Base\Deploy
          calls:
              -
                   method:  injectEventDispatcher
                   arguments:
                       -    '@event_dispatcher'
    build_config:
          class:           Deploy\Extensions\Base\Config\BuildConfig
    execute_local:
          class:           Deploy\Extensions\Base\Service\ShellExecutor\Local
    execute_remote:
          class:           Deploy\Extensions\Base\Service\ShellExecutor\Remote
    execute_rsync:
          class:           Deploy\Extensions\Base\Service\ShellExecutor\Rsync
